"""Added new columns to User

Revision ID: 0e8d88eadc28
Revises: d4867f3a4c0a
Create Date: 2021-12-03 15:26:30.577191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8d88eadc28'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('salt', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('private_key', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('verify_key', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('added_by', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('institution', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'institution')
    op.drop_column('user', 'website')
    op.drop_column('user', 'added_by')
    op.drop_column('user', 'verify_key')
    op.drop_column('user', 'private_key')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'budget')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
