"""Dropped User Role

Revision ID: 0f28f7ae2a74
Revises: 429ae74b421a
Create Date: 2021-12-24 15:23:54.805270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f28f7ae2a74'
down_revision = '429ae74b421a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_fkey', 'user', 'role', ['role'], ['id'])
    # ### end Alembic commands ###
