"""Requests

Revision ID: 44a3ca1f48f1
Revises: c0bded2371ed
Create Date: 2022-02-05 23:29:29.217129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44a3ca1f48f1'
down_revision = 'c0bded2371ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_request',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('data_subjects', sa.Integer(), nullable=True),
    sa.Column('linked_datasets', sa.String(length=255), nullable=True),
    sa.Column('request_size', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=2048), nullable=True),
    sa.Column('result_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('num_of_values', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('reviewer_comments', sa.String(length=2048), nullable=True),
    sa.Column('request_owner', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['request_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrade_request',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('domain', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('requested_budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=2048), nullable=True),
    sa.Column('result_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('reviewer_comments', sa.String(length=2048), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('request_owner', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['domain'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['request_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upgrade_request')
    op.drop_table('data_request')
    # ### end Alembic commands ###
