"""Adding fields to Domain

Revision ID: 4a8e45259349
Revises: d1fc8d45343c
Create Date: 2022-01-24 21:59:10.344395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8e45259349'
down_revision = 'd1fc8d45343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('require_daa', sa.Boolean(), nullable=True))
    op.add_column('domain', sa.Column('domain_url', sa.String(length=255), nullable=True))
    op.add_column('domain', sa.Column('pdf_daa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'domain', 'daa_pdf', ['pdf_daa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='foreignkey')
    op.drop_column('domain', 'pdf_daa_id')
    op.drop_column('domain', 'domain_url')
    op.drop_column('domain', 'require_daa')
    # ### end Alembic commands ###
