"""Created Requests tables

Revision ID: 5cee5bafb4b3
Revises: c0bded2371ed
Create Date: 2022-02-05 18:36:07.248391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cee5bafb4b3'
down_revision = 'c0bded2371ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
