"""Added roles

Revision ID: 752523fb0742
Revises: b8e015189b3d
Create Date: 2021-12-10 12:28:34.232092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752523fb0742'
down_revision = 'b8e015189b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('can_make_data_requests', sa.Boolean(), nullable=True),
    sa.Column('can_triage_data_requests', sa.Boolean(), nullable=True),
    sa.Column('can_manage_privacy_budget', sa.Boolean(), nullable=True),
    sa.Column('can_create_users', sa.Boolean(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=True),
    sa.Column('can_edit_roles', sa.Boolean(), nullable=True),
    sa.Column('can_manage_infrastructure', sa.Boolean(), nullable=True),
    sa.Column('can_upload_data', sa.Boolean(), nullable=True),
    sa.Column('can_upload_legal_document', sa.Boolean(), nullable=True),
    sa.Column('can_edit_domain_settings', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.drop_table('role')
    # ### end Alembic commands ###
