"""Adding DAA

Revision ID: b8e015189b3d
Revises: 0e8d88eadc28
Create Date: 2021-12-06 15:59:59.190917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e015189b3d'
down_revision = '0e8d88eadc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daa_pdf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binary', sa.LargeBinary(length=3072), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('daa_pdf', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'daa_pdf', ['daa_pdf'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'daa_pdf')
    op.drop_table('daa_pdf')
    # ### end Alembic commands ###
