"""Added allocated_budget

Revision ID: c0bded2371ed
Revises: 4a8e45259349
Create Date: 2022-01-26 13:17:18.906944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bded2371ed'
down_revision = '4a8e45259349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allocated_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'allocated_budget')
    # ### end Alembic commands ###
