"""Added last_updated field to domain

Revision ID: d1fc8d45343c
Revises: eee10b098b64
Create Date: 2022-01-22 14:25:06.175538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fc8d45343c'
down_revision = 'eee10b098b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'last_updated')
    # ### end Alembic commands ###
