"""Missing fields requests

Revision ID: fc4dc8a50b5c
Revises: 44a3ca1f48f1
Create Date: 2022-02-06 14:49:30.502508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc4dc8a50b5c'
down_revision = '44a3ca1f48f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_request', sa.Column('domain', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('data_request', sa.Column('requester_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'data_request', 'domain', ['domain'], ['id'])
    op.add_column('upgrade_request', sa.Column('request_owner_name', sa.String(length=255), nullable=True))
    op.add_column('upgrade_request', sa.Column('initial_budget', sa.Float(), nullable=True))
    op.add_column('upgrade_request', sa.Column('allocated_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade_request', 'allocated_budget')
    op.drop_column('upgrade_request', 'initial_budget')
    op.drop_column('upgrade_request', 'request_owner_name')
    op.drop_constraint(None, 'data_request', type_='foreignkey')
    op.drop_column('data_request', 'requester_name')
    op.drop_column('data_request', 'domain')
    # ### end Alembic commands ###
